### ISSUE TITLE
git bash problem

### ISSUE THREAD

**Issue by gunhuikim** [kimmikimmi/leetcode_problem_solving#4]
if i type " $ git push --set-upstream origin master" in git bash
it keeps saying like this ( I typed my ID and P/W right)
" 

remote: Permission to kimmikimmi/leetcode_problem_solving.git denied to gunhuikim.
fatal: unable to access 'https://github.com/kimmikimmi/leetcode_problem_solving.git/': The requested URL returned error: 403
"

**Comment by kimmikimmi** [comment]
did you sort it out?

**Comment by kimmikimmi** [comment]
I added you as a collaborator,  which means you are currently one of owners of this repository.
