### ISSUE TITLE
LG code jam problems

### ISSUE THREAD

**Issue by gunhuikim** [kimmikimmi/leetcode_problem_solving#5]
refer the attached
[A번_ 카드 바꿔치기.pdf](https://github.com/kimmikimmi/leetcode_problem_solving/files/4427381/A._.pdf)
[B번_ 조교 배치.pdf](https://github.com/kimmikimmi/leetcode_problem_solving/files/4427382/B._.pdf)
[C번_ 팀 배정.pdf](https://github.com/kimmikimmi/leetcode_problem_solving/files/4427383/C._.pdf)
[D번_ 그리드 네트워크.pdf](https://github.com/kimmikimmi/leetcode_problem_solving/files/4427384/D._.pdf)
[E번_ 불안정한 물질.pdf](https://github.com/kimmikimmi/leetcode_problem_solving/files/4427385/E._.pdf)
[F번_ 오픈소스 버그 잡기.pdf](https://github.com/kimmikimmi/leetcode_problem_solving/files/4427386/F._.pdf)

**Comment by gunhuikim** [comment]
Solution for A

test_case= int(input()) #Total test cases

for i in range(0, test_case):

    n: int(input()) #num of cards

    origin_list = list(map(str, input().split()))
    bum_list = list(map(str, input().split()))


    if sorted(origin_list) == sorted(bum_list):
        print("NOT CHEATER")

    else:
        print("CHEATER")

**Comment by kimmikimmi** [comment]
Maybe try it next time. :)
